export default {
  css:{
    opacity: 1,
    height:400,
    width:500,
    backgroundColor:'#fff',
    module_left: 0,
    module_top: 0,
    module_width: 200,
    module_height: 200,
    module_name: "",
    module_lock: false,
    w_border_raduis_num: 0,
    w_opacity: 1,
    w_fill: 0,
    w_transtion: 0,
    w_border_left_style: 'solid',
    w_border_left_width: 0,
    w_border_top_style: 'solid',
    w_border_top_width: 0,
    w_border_right_style: 'solid',
    w_border_right_width: 0,
    w_border_bottom_style: 'solid',
    w_border_bottom_width: 0,
    w_tile_style: 'repeat',
    module_pulick_border_top_color: "#000",
    module_pulick_border_right_color: "#000",
    module_pulick_border_bottom_color: "#000",
    module_pulick_border_left_color: "#000",
    w_background: "#fff",
    w_bg_src:'',
    w_bg_position:''
  }
};
