export default {
    infor: {
        goback_function_style: 'back',
        goback_top_distance: 0,
        goback_a_width: 120,
        goback_a_height: 60,
        goback_a_border_radiu: 0,
        goback_a_fs_color: '#000',
        goback_a_bc_color: '#f0f',
        goback_a_fs_color_hover: '#fff',
        goback_a_bc_color_hover: '#f0f',
        goback_icon_fs_color: '#fff',
        goback_icon_fs_color_hover: '#fff',
        goback_a_text_align: 'center',
        goback_a_fs: 14,
        goback_icon_fs: 14,
        goback_a_padding_left: 0,
        goback_a_padding_right: 0,
        goback_icon_left: 0,
        goback_icon_top: 0,
        goback_icon_class: 'fa-mail-reply',
        goback_a_txt: '返回',
        goback_a_border_style: "solid",
        goback_a_border_style_hover: "solid",
        goback_a_border_width: 0,
        goback_a_border_width_hover: 0,
        goback_a_border_color: '#000',
        goback_a_border_color_hover: '#000',
        widget_loading: "基础",
        widget_loading_li: "无动画",
        widget_animateds: "",
        widget_scroll_loading_checked: false,
        widget_scroll_loading: false,
        widget_scroll_loading_location_checked: false,
        widget_scroll_loading_location: false,
        widget_scroll_loading_location_height: 0,
        pic_iteration_checked2: false,
        pic_iteration2: "no",
        animation_countsss: 1,
        animation_durasss: 1,
        animation_delaysss: 0,
    }, listArr: {

    },
    animateObj: {
        animatedType: '',
        animatedDuration: 0.5,
        animatedDelay: 0,
        animatedIterationCount: false,
        animatedState: '',
    }
}