export default {
    infor:{
        picStyle:'0',
        date_mr:0,
        picture_width:200,
        year:'年',
        month:'月',
        day:'日',
        hours:'时',
        minutes:'分',
        seconds:'秒',
        date_is_show:'block',
        time_is_show:'block',
        date_fs:16,
        time_fs:16,
        date_color:"#000",
        time_color:"#000",
        width:400,
        height:44
    },listArr:{
        
    },
    animateObj:{
      animatedType:'',
      animatedDuration:0.5,
      animatedDelay:0,
      animatedIterationCount:false,
      animatedState:'',
    }
}