export default {
  infor: {
    picStyle: '0',
    graWidth: 184,
    graHeight: 80,
    border_gra_c: "#000",
    gra_url: '',
    w_gra_describe: '',
    gra_target: '_self',
    animation_duras: 1,
    animation_delays: 0,
    animation_counts: 1,
    gra_style_opacity: 100,
    border_gra_s: 'solid',
    border_gra_w: 0,
    border_radius_s: 0,
    animation_dura: 1,
    animation_delay: 0,
    animation_count: 1,
    gra_opacity1: 100,
    border_s: 'solid',
    border_w: 0,
    border_radius_h: 0,
    animation_durasss: 1,
    animation_delaysss: 0,
    animation_countsss: 1,
    gra_margin_top: 0,
    gra_margin_bottom: 0,
    gra_margin_left: 0,
    gra_margin_right: 0,
    contents: '',
    imgUrl: '',
    pic_loading: "基础",
    pic_loading_li: "无动画",
    pic_loading_hover: "基础",
    pic_loading_hover_li: "无动画",
    widget_loading: "基础",
    widget_loading_li: "无动画",
    widget_animateds: "",
    pic_animateds: "",
    pic_new_animateds: "",
    pic_new_animateds_hover: "",
    pic_iteration: "no",
    pic_iteration_checked: false,
    pic_iteration1: "no",
    pic_iteration_checked1: false,
    pic_iteration2: "no",
    pic_iteration_checked2: false,
    pic_scroll_loading_checked: false,
    pic_scroll_loading: false,
    widget_scroll_loading_checked: false,
    widget_scroll_loading: false,
    pic_scroll_loading_location_checked: false,
    pic_scroll_loading_location: false,
    widget_scroll_loading_location_checked: false,
    widget_scroll_loading_location: false,
    pic_scroll_loading_location_height: 0,
    widget_scroll_loading_location_height: 0,
    width:200,
    height:200
  }, listArr: {

  },
  animateObj: {
    animatedType: '',
    animatedDuration: 0.5,
    animatedDelay: 0,
    animatedIterationCount: false,
    animatedState: '',
  }
}