export default {
  infor:{
    module_width:900,
    module_height:666,
    module_index:1,
    module_name:"",
    w_border_raduis_num:0,
    w_opacity:1,
    w_fill:0,
    w_transtion:0,
    w_background:"#e5e5e5",
    w_border_left_color:'#333',
    w_border_left_style:'solid',
    w_border_left_width:1,
    w_border_top_color:'#333',
    w_border_top_style:'solid',
    w_border_top_width:1,
    w_border_right_color:'#333',
    w_border_right_style:'solid',
    w_border_right_width:1,
    w_border_bottom_color:'#333',
    w_border_bottom_style:'solid',
    w_border_bottom_width:1,
    w_tile_style:'repeat',
    w_bg_src:'',
    w_bg_position:'top left',
    r_bg_src:'',
    r_bg_position:'top left',
    r_background:"#fff",
    r_border_top_style:'solid',
    r_border_top_width:1,
    r_border_top_color:'#ccc',
    r_border_bottom_width:1,
    r_border_bottom_style:'solid',
    r_border_bottom_color:'#ccc',
    r_fill:0,
    r_tile_style:'repeat',
    fixed:'static',
    rowId:'',

  }
};
